language: cpp
compiler:
- gcc

before_install:
# make backports of gcc available on trusty
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
- sudo apt-get update

install:
- scripts/get-cmake.sh
- scripts/get-boost.sh

# get gcc to a C++14 compatible version
- sudo apt-get -y -qq install gcc-4.9 g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90

before_script:
- echo "$(cmake --version)
        $(gcc --version)
        "
- mkdir build && cd build
- cmake ..

script:
- make all
- cd test && ctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce99bff09d11703eff7
    on_success: change
    on_failure: always
    on_start: false
